// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#pragma warning disable CS9084 // Struct member returns 'this' or other instance members by reference

namespace TWin
{
    public unsafe partial class TView
    {
        public partial struct __Internal
        {
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::TWin.TView> NativeToManagedMap =
            new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::TWin.TView>();

        internal static void __RecordNativeToManagedMapping(IntPtr native, global::TWin.TView managed)
        {
            NativeToManagedMap[native] = managed;
        }

        internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::TWin.TView managed)
        {
    
            return NativeToManagedMap.TryGetValue(native, out managed);
        }

        protected bool __ownsNativeInstance;

        internal static TView __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            return new TView(native.ToPointer(), skipVTables);
        }

        internal static TView __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (__TryGetNativeToManagedMapping(native, out var managed))
                return (TView)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                __RecordNativeToManagedMapping(native, result);
            return result;
        }

        internal static TView __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new TView(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            *(__Internal*) ret = native;
            return ret.ToPointer();
        }

        private TView(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
        }

        protected TView(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }
    }

    public unsafe partial class TWin : IDisposable
    {
        [StructLayout(LayoutKind.Sequential, Size = 8)]
        public partial struct __Internal
        {
            internal uint _width;
            internal uint _height;

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "??0TWin@@IEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr ctor(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "??0TWin@@QEAA@AEBV0@@Z", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr cctor(__IntPtr __instance, __IntPtr _0);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "??1TWin@@QEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void dtor(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?create@TWin@@SAPEAV1@PEAV1@_N@Z", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr Create(__IntPtr win, bool with_border);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?resize@TWin@@QEAAXHH@Z", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void Resize(__IntPtr __instance, int w, int h);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?realize_context@TWin@@QEAAXXZ", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void RealizeContext(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?exec@TWin@@QEAAX_N@Z", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void Exec(__IntPtr __instance, bool thead);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?load_model@TWin@@QEAAXPEBDM@Z", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void LoadModel(__IntPtr __instance, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(CppSharp.Runtime.UTF8Marshaller))] string file, float sz);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?handle@TWin@@QEAA_KXZ", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern ulong Handle(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("FilaView.dll", EntryPoint = "?view@TWin@@QEAAPEAVTView@@XZ", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr View(__IntPtr __instance);
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::TWin.TWin> NativeToManagedMap =
            new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::TWin.TWin>();

        internal static void __RecordNativeToManagedMapping(IntPtr native, global::TWin.TWin managed)
        {
            NativeToManagedMap[native] = managed;
        }

        internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::TWin.TWin managed)
        {
    
            return NativeToManagedMap.TryGetValue(native, out managed);
        }

        protected bool __ownsNativeInstance;

        internal static TWin __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            return new TWin(native.ToPointer(), skipVTables);
        }

        internal static TWin __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (__TryGetNativeToManagedMapping(native, out var managed))
                return (TWin)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                __RecordNativeToManagedMapping(native, result);
            return result;
        }

        internal static TWin __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new TWin(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            *(__Internal*) ret = native;
            return ret.ToPointer();
        }

        private TWin(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
        }

        protected TWin(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        protected TWin()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::TWin.TWin.__Internal));
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
            __Internal.ctor(__Instance);
        }

        public TWin(global::TWin.TWin _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::TWin.TWin.__Internal));
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
            *((global::TWin.TWin.__Internal*) __Instance) = *((global::TWin.TWin.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true, callNativeDtor: __ownsNativeInstance);
        }

        partial void DisposePartial(bool disposing);

        internal protected virtual void Dispose(bool disposing, bool callNativeDtor)
        {
            if (__Instance == IntPtr.Zero)
                return;
            NativeToManagedMap.TryRemove(__Instance, out _);
            DisposePartial(disposing);
            if (callNativeDtor)
                __Internal.dtor(__Instance);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public void Resize(int w, int h)
        {
            __Internal.Resize(__Instance, w, h);
        }

        public void RealizeContext()
        {
            __Internal.RealizeContext(__Instance);
        }

        public void Exec(bool thead)
        {
            __Internal.Exec(__Instance, thead);
        }

        public void LoadModel(string file, float sz)
        {
            __Internal.LoadModel(__Instance, file, sz);
        }

        public static global::TWin.TWin Create(global::TWin.TWin win, bool with_border)
        {
            var __arg0 = win is null ? __IntPtr.Zero : win.__Instance;
            var ___ret = __Internal.Create(__arg0, with_border);
            var __result0 = global::TWin.TWin.__GetOrCreateInstance(___ret, false);
            return __result0;
        }

        protected uint Width
        {
            get
            {
                return ((__Internal*)__Instance)->_width;
            }

            set
            {
                ((__Internal*)__Instance)->_width = value;
            }
        }

        protected uint Height
        {
            get
            {
                return ((__Internal*)__Instance)->_height;
            }

            set
            {
                ((__Internal*)__Instance)->_height = value;
            }
        }

        public ulong Handle
        {
            get
            {
                var ___ret = __Internal.Handle(__Instance);
                return ___ret;
            }
        }

        public global::TWin.TView View
        {
            get
            {
                var ___ret = __Internal.View(__Instance);
                var __result0 = global::TWin.TView.__GetOrCreateInstance(___ret, false);
                return __result0;
            }
        }
    }
}
